### ISSUE TITLE
Deleting an attempt throws a server error

### ISSUE THREAD

**Issue by ugoertz** [numbas/numbas-lti-provider#119]
When deleting an attempt (as an "instructor", using the "Delete" link in the list of attempts), the attempt is deleted from the database, but the `send_receipt_on_completion` signal method fails because it fails to retrieve the deleted attempt (since the objects manager returns only attempts with `deleted == False`).

**Comment by christianp** [comment]
Thanks for reporting this. I ran into it myself today.
