### ISSUE TITLE
No scores being sent to VLE

### ISSUE THREAD

**Issue by oscarsiles** [numbas/numbas-lti-provider#133]
Ever since upgrading to version 2.10 of the LTI provider (and setting up huey according to the upgrade instructions) no scores are being sent back to the VLE. This affects both automatic score updates through the "When to report scores back" setting or manually via the yellow button on the activity dashboard. The latter would normally show a banner showing that this was pending (and then turned green I believe when complete), but this no longer appears.

I've checked the various worker logs and can't seem to find anything related to this issue, so I wonder if there's an additional change needed for score updates to work?

EDIT: I can see there is a steady stream of diff_suspend_data tasks running from the huey logs, so I wonder if the score reporting is stuck at the back of this queue? I updated roughly 2 weeks ago so find this unlikely unless the process of diff-ing really is that slow (we have about 7,000 attempts saved currently).

However, it seems that recently completed diff tasks were queued up several days ago, and over 13,000 have been completed since upgrading (nearing double the amount of attempts). The CPU's 8 threads are at a near constant 100% with postgres processes which I assume is related. I wonder if caching the results may help, if not being done already?

**Comment by christianp** [comment]
The diff tasks are set to run periodically, so they should leave time for the other tasks. Diffing is quite slow, but we have a couple of orders of magnitude more attempts than you and I don't think score reporting has been affected.

I suppose you could try removing the `diff_suspend_data` task from `numbas_lti/tasks.py`, and see if scores start being reported again?

**Comment by oscarsiles** [comment]
It does appear that scores are sent to the VLE (we use Moodle) _sometimes_, but if the "Immediately" option is selected then not all updated scores are reflected in Moodle. Changing it to "On Completion" seems to have mostly bypassed the issue, except the "Report scores back to the VLE" button seems to only work occasionally (can't figure out why). Looking at the logs, the `resource_report_scores` task is barely ever being queued (not sure if this is the task called by pressing that button).

I've tried removing the diff task from the code, but it then just spams an error about the task not existing and that seems to hammer 2 threads constantly. I wonder if implementing task priorities could help make sure the diff task is always at the back of the queue...

Will try to investigate more after our next set of coursework is finalized.

**Comment by oscarsiles** [comment]
Turns out it was just lagging behind on all the diff tasks, and now that it has caught up it has a delay of up to a minute max. Still may be worth considering adding priorities to tasks (if possible), but I just needed to be a bit more patient in the end; took over a month for the diffs to complete!
