### ISSUE TITLE
Update docs for 2.11 release

### ISSUE THREAD

**Issue by peterlcsteele** [numbas/numbas-lti-provider#144]
In the manual steps for the 2.11 release, I've noticed a few issues:
In **numbasltiprovider/settings.py**:

`'django_token'` is shown in `INSTALLED_APPS` sample. I believe this has been included erroneously?

If the `LANGUAGE_CODE = 'en-us'`, after upgrading to 2.11 the LTI integration will become unusable and parts of the admin UI will not render properly. After a bit of digging, I found that 'en-us' is not a valid dir inside **numbas-lti-static/jsi18n** - changing the **LANGUAGE_CODE** value to either 'en', 'en-gb' or 'en-au' appears to fix the issue.

Also, in the manual steps for 2.10:
Please confirm that **www-data** (Ubuntu) or **nginx** (RHEL) is the correct user for the new huey task runner and not **numbas_lti** as the other supervisord processes.
```user=www-data```

Thank you, Peter

**Comment by christianp** [comment]
Thanks for pointing these out. `django_token` was indeed included by mistake.

On Ubuntu, I don't think it matters whether the huey task runs as `www-data` or `numbas_lti`. I can't easily test on RHEL, so I've changed it to `numbas_lti` because that definitely works.
