### ISSUE TITLE
There's a timing issue with reporting scores

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider#164]
I set up a Numbas assignment in Canvas, and started an attempt as a student. I got the first part correct, so my score was 1/20. The Canvas grade book shows a score of 0, so it looks like the reporting happened before my total was saved.

**Comment by christianp** [comment]
This doesn't happen in my local Moodle.

**Comment by christianp** [comment]
But does happen on our production Moodle!

**Comment by christianp** [comment]
This does seem to be a timing issue: I can reproduce this when I run the workers and huey in separate processes, using redis to store the task queue.

Adding a delay to the task to report outcomes fixes the problem, so the post_save signal for ScormElements is probably within a database transaction that isn't finished when the report outcome task runs. (see #162)

Unfortunately, scheduling tasks needs redis-py>=3, and asgi-redis needs redis-py<3, so there's a dependency conflict. I think this can only be resolved by moving to django-channels 2, which is well overdue anyway.

I tried installing the latest redis-py anyway,  and it looks like it works, but that's not a good situation to be in.

We're still in our resit period, so I can't test on our live server.

**Comment by dman445** [comment]
I'd like to add that we are experiencing a similar issue with Moodle. Here is how to replicate the error. 

Take a NUMBAS exam with two parts, and change the exam setting "When to report scores back" to "Immediately". When I complete the exam, NUMBAS shows that I have a score of 100% (naturally) but only the marks for the first question are reported back to Moodle.

Changing the settings "When to report scores back" from "Immediately" to "On completion" fixes the problem for me.
