### ISSUE TITLE
Docker install - Django/Numbas-LTI incompatible with psycopg2 > 2.8.6

### ISSUE THREAD

**Issue by peterlcsteele** [numbas/numbas-lti-provider#174]
Django/Numbas-LTI seems to be incompatible with psycopg2 > 2.8.6. 

After following instructions, on first login **Internal Server Error 500** displayed in browser.
The following error is thrown server-side:
```
AssertionError: database connection isn't set to UTC
```

Suggest installing/requiring v2.8.6 in Dockerfile:
```
RUN python3 -m pip install asgi_redis psycopg2==2.8.6 django-environ
```
See: https://stackoverflow.com/questions/68024060/assertionerror-database-connection-isnt-set-to-utc

**Comment by christianp** [comment]
Thanks for reporting this!
