### ISSUE TITLE
Per-consumer option to specify OAuth field containing user id

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider#20]
Blackboard sends the user's ID in `user_id`, while Moodle uses `lis_person_sourcedid`. I think Moodle is correct, but since BB is an immovable object, we should be able to specify per-consumer what the user ID field is.

**Comment by wade-tattersall** [comment]
For what it's worth, new versions of Blackboard use `lis_person_sourcedid` too. It also sends a `user_id` that is not human-readable (eg: 10689a660f694ad9b9129afa844b5991). I think it became that way when we moved from Managed Hosting to SaaS in December 2017.

**Comment by christianp** [comment]
@wade-tattersall Thanks. Do you have a version number for Blackboard

**Comment by wade-tattersall** [comment]
At the moment we are on v3400.5.0, as per the SaaS-specific [version numbering](https://help.blackboard.com/Learn/Administrator/SaaS/Release_Notes/Learn_SaaS_Release_Schedule). I suspect the change came about in the move to SaaS though, so it would have been the case as far back as v3100.0.0

**Comment by christianp** [comment]
Thanks!

**Comment by christianp** [comment]
I think this is fixed by 9203bb8a181e9f5c6160f26e0086bd9405c3e5f1
