### ISSUE TITLE
Numbas not automatically writing grades back to Canvas.

### ISSUE THREAD

**Issue by fbonatto** [numbas/numbas-lti-provider#208]
An instructor has reported today that Numbas is still not automatically writing grades back to Canvas. They've reported that the manual option of 'report scores back to VLE' is still working. I believe we're still on 2.13.2. Has this been resolved in more recent release?

**Comment by christianp** [comment]
Always worth upgrading! v2.14 fixed a problem with out of date scores being reported. v3.0 added priorities for tasks, which might help.

**Comment by christianp** [comment]
@fbonatto the change in #211 might help with this.
