### ISSUE TITLE
Numbas appears to not be calculating score properly

### ISSUE THREAD

**Issue by fbonatto** [numbas/numbas-lti-provider#215]
Message received from an instructor:

Please could you look into an issue that a couple of my students have highlighted. The LTI does not seem to be calculating the score correctly as a percentage. For example, in the case shown in the attached screenshot, notice the third attempt scored 10/12 but
this is recorded as 58%, whereas it should be 83%.

It is not happening very often, so it’s hard to see any pattern. Indeed, as you can see in this case, it only affected one
of the student’s four attempts at the test.

Thanks for any light you can shed on this!

![image](https://user-images.githubusercontent.com/98384572/156354632-dc546c2c-3281-4d51-b964-ee8e9d56af9e.png)

**Comment by christianp** [comment]
This can happen when the task to compute the scaled score is delayed. I made some changes to try to avoid this recently - can you tell me which version of the LTI tool you're running? If you can give the hash of the commit you're using, that would be very helpful.

**Comment by fbonatto** [comment]
Thanks Christian, the hash of the commit we're currently using is
4df5b49bd821bb098036c06249a0090e050caad2

**Comment by christianp** [comment]
That's v2.13.2. v3.0 should avoid this kind of problem.
