### ISSUE TITLE
Manual re-mark only allows updated scores to 1 decimal place

### ISSUE THREAD

**Issue by chrismgraham** [numbas/numbas-lti-provider#222]
The manual re-mark page (remark_parts) can only allocate marks to 1 decimal place in the updated score. So if a part is worth 0.75 marks then it is not possible to allocate more than 0.7 marks.

**Comment by juliaramosgonzalez** [comment]
Could this be implemented as well for a question that is worth 0.125? I am only able to re-mark this question manually using 2 decimal places.
