### ISSUE TITLE
Score and attempt CSVs may contain inconsistent scores 

### ISSUE THREAD

**Issue by chrismgraham** [numbas/numbas-lti-provider#237]
One case of this known at Newcastle: https://mas-numbas-lti.ncl.ac.uk/resource/5605

In tasks.py, `attempt.raw_score` (used in the attempts CSV) seems to be the reliable score. The % in the _Attempts CSV_ and both the raw and % in the _Scores CSV_ seem to depend on `attempt.scaled_score` which isn't apparently always the final attempt score.

**Comment by christianp** [comment]
This is the same issue as #289.
