### ISSUE TITLE
django_session data not expiring

### ISSUE THREAD

**Issue by lgretton** [numbas/numbas-lti-provider#255]
The second largest database table in our installation is the django_session one, which for us has grown to 14 million entries and 6GB in the last two years. This is using MariaDB as the backend.

Reading the [Django session documentation](https://docs.djangoproject.com/en/4.1/topics/http/sessions/#clearing-the-session-store), this table is supposed to be periodically purged of old data, but for the LTI Provider this isn't happening, and I can't find anything in the docs that references it.

Have I overlooked something I'm supposed to have done with our installation to get this table purged from time to time? Do I have to manually set up a cron job to run clearsessions myself?

**Comment by christianp** [comment]
Oh whoops, you're right! Our sessions table also has a couple of million entries.

The documentation there says that you should set up a cron job to run `python manage.py clearsessions` regularly. I'll add that to the installation instructions.
