### ISSUE TITLE
Safe Exam Browser not opening automatically + no download link provided

### ISSUE THREAD

**Issue by Spruce8913** [numbas/numbas-lti-provider#276]
Steps to reproduce: using Numbas LTI provider and Blackboard Ultra, add an LTI link in BB ultra to a resource on Numbas LTI provider requiring Safe Exam Browser. When clicked, following page opens:
![image](https://github.com/numbas/Numbas/assets/49608009/73dd64c6-e8bc-4c49-892a-ae42625754c1)

Two issues:
- Even though Safe Exam Browser is installed, it does not open automatically. Only after pressing the blue button, it opens.
- No download link for Safe Exam Browser is displayed, unlike when using Numbas lockdown app.

**Comment by christianp** [comment]
It looks like the code to automatically launch the app was commented out - I must have left it that way by mistake during testing.

The "install Safe Exam Browser" button is there for me. It's shown if the setting `LOCKDOWN_APP['seb_install_url']` is set in your `numbasltiprovider/settings.py`. Can you check it's there? The default value is given in `numbasltiprovider/settings.py.dist`.
