### ISSUE TITLE
SEB on mac: quit link not working on mac (any mac version)

### ISSUE THREAD

**Issue by Spruce8913** [numbas/numbas-lti-provider#281]
When clicked on mac, receives the error message "you were not supposed to see this". The button "Go Back" then does not respond to clicks. This is on SEB version 3.2.5 and many different versions of mac (in exam hall of 100 students the quit link was not working for anyone with a mac, around 50 students).

**Comment by mjmq100** [comment]
I see this with SEB 3.2.5 on macOS 13.5.2 and v3.2 of the LTI provider. I think SEB is looking for an exact match for the quit URL supplied in its config, but the provider tacks on a resource_link_id query parameter when generating the URL from within an attempt. (Generated in numbas_lti/context_processors.py I think, but it seems the parameter is added in middleware?).

To test this, in my SEB config file I appended a query string to the quit URL to include the resource_link_id associated with my test. With this the quit URL works.

I can imagine some ugly workarounds, but I'm not sure what a robust solution would be.
