### ISSUE TITLE
Also request password *after* locking down in SEB

### ISSUE THREAD

**Issue by Spruce8913** [numbas/numbas-lti-provider#295]
In our setting we use BYOD-exams with Numbas+SEB. I have realised students' laptops are only locked down *after* filling in the SEB password. This means they cannot communicate during the exam, but they can still send the password itself in a groupchat to students who are not present in the exam hall which still allows them to participate (with external help).

Would it be possible to request another password, right before the exam (so when "Start" is clicked), after the laptop is already locked down?

**Comment by christianp** [comment]
If I've understood correctly what you're asking for, this is what the [Password to begin the exam](https://docs.numbas.org.uk/en/latest/exam/reference.html#term-Password-to-begin-the-exam) setting is for.

**Comment by Spruce8913** [comment]
Thank you for the superfast response. This is exactly what I was looking for.
