### ISSUE TITLE
Show some stats in the instructor dashboard

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider#3]
- A score distribution graph would be nice.
- Number of attempts, and percent completed.
- Some item analysis - discrimination index, and easiest/hardest question?

Could copy some stuff from the blackboard analysis tool.

Show frequencies of the following break-downs:

- completion status
- pass/fail
- number of questions attempted

**Comment by ilogin** [comment]
Can you delegate this to me? I can work on adding a score distribution graph and the number of attempts and percent completed.

**Comment by christianp** [comment]
Hi,
Thanks for offering to help. I won't assign this issue to you because I don't know who you are, but I'm interested to see what you come up with. Please make a pull request once you've written some code.

**Comment by chrismgraham** [comment]
Quartiles and mean in the statistics tab would be great. 

And something like the question heatmaps, but across the whole cohort, would be useful as an overview of which questions were easy/difficult.
