### ISSUE TITLE
Mixture of usernames and email addresses in recording attempts

### ISSUE THREAD

**Issue by msgj603** [numbas/numbas-lti-provider#302]
![image](https://github.com/numbas/Numbas/assets/5709336/bf00b778-1f76-4381-b4a6-81d7c34eaa53)
Please see image. Sometimes Numbas records the username as the userID and sometimes it is the whole email address. Is there a reason for this inconsistency? It is difficult when giving a student extra time or another attempt, because you don't know what to type for the username.

**Comment by christianp** [comment]
@msgj603 can we close this?

**Comment by msgj603** [comment]
I still don't have any explanation for this, but if it's only me that's seeing it then I guess so
