### ISSUE TITLE
LTI 1.3: Canvas Test Students appear with no name

### ISSUE THREAD

**Issue by Lycanic** [numbas/numbas-lti-provider#308]
When testing using Canvas, using their 'student view' to test exams, student names are empty rather than 'Test Student' or similar.

![image](https://github.com/numbas/numbas-lti-provider/assets/17724612/20194da7-856c-4508-8293-d261b5b8f7b9)

(This may be a case of needing a default name, or something particular to identify a 'test student'.)

**Comment by christianp** [comment]
This was because Canvas was set to "private" mode, instead of "public". I've changed the default Canvas config.
