### ISSUE TITLE
LTI 1.3: Adding access change MissingSchema error

### ISSUE THREAD

**Issue by Lycanic** [numbas/numbas-lti-provider#309]
Clicking '+ Add an access change' results in an error:
MissingSchema at /resource/5/access_change/create

**Comment by christianp** [comment]
We hadn't set the `auth_token_url` property on the `LtiTool` object.
For production, it's `https://canvas.instructure.com/login/oauth2/token` (from https://community.canvaslms.com/t5/Canvas-Developers-Group/LTI-1-3-OIDCAuth-url/m-p/216910)
