### ISSUE TITLE
Safari security change required to access tests

### ISSUE THREAD

**Issue by chrismgraham** [numbas/numbas-lti-provider#325]
Students this week complained of not being able to access tests, getting the message "This URL is supposed to be used to launch an LTI activity"

Not sure if it's because of a change in the tool configuration or just be because they're new students to Numbas, but seemed they were Safari users and it was necessary to untick _Prevent cross-site tracking_.

**Comment by christianp** [comment]
I've tried with "Prevent cross-site tracking" turned on, and it just showed me the "open in a new window" link, but the link opened properly in the new window.

**Comment by chrismgraham** [comment]
I get that too today. I wonder if this was related to the cookie problems earlier in the week... anyway seems OK now
