### ISSUE TITLE
Running numbas under a sub-path

### ISSUE THREAD

**Issue by wade-tattersall** [numbas/numbas-lti-provider#52]
We'd like to run several small LTIs on the same server. To that end, I've made Numbas work on a sub-path, `lti.example.com/numbas/lti_entry`, etc.

This is what I've done with urls.py at the moment:

```
-    url(r'^admin/', admin.site.urls),
-    url(r'^', include('numbas_lti.urls')),
+    url(r'^numbas/admin/', admin.site.urls),
+    url(r'^numbas/', include('numbas_lti.urls')),
```
as well as similar changes to `routing.py`.

I've modified MEDIA_URL, STATIC_URL and the mappings in the nginx conf as well.

It works quite well, but perhaps it is not ideal to have to edit anything other than `settings.py`. Is it possible to do this by setting something in `settings.py`. Perhaps I could add a 'URL_PREFIX' setting or similar?

**Comment by christianp** [comment]
It looks like you just need to give the `--root-path=/numbas` option to the daphne process. [Here's the relevant bit of the daphne docs](https://github.com/django/daphne#root-path-script_name).
