### ISSUE TITLE
When sending a lis_person_sourcedid over 25 characters, the username is truncated

### ISSUE THREAD

**Issue by dcollien** [numbas/numbas-lti-provider#58]
I've been troubleshooting an issue where every unique VLE user ends up signed in as the same NUMBAS user. The problem seems to be that the first 25 characters of the lis_person_sourcedid are the same for each user (as is evident in the CSV reporting) and the rest (the unique portion) is truncated.

**Comment by christianp** [comment]
That's unfortunate! Can you email me some more details at christian.perfect@ncl.ac.uk? Which VLE are you using?

**Comment by christianp** [comment]
The max length for a username is now 150 characters, so I think given that I didn't get any more details, this is probably not going to happen again.
