### ISSUE TITLE
Review button still present (but hidden) even when set to never show scores

### ISSUE THREAD

**Issue by oscarsiles** [numbas/numbas-lti-provider#61]
When setting the option "When to show scores to students" to never, the button to review the attempt is still present and clickable (leads to results summary if enabled), even though it looks like a blank space. See image below.

![image](https://user-images.githubusercontent.com/48240545/54428462-7ab3cd80-4715-11e9-83a8-9960e128aaf0.png)

**Comment by christianp** [comment]
Thanks for reporting this. I've fixed it, so the button isn't rendered at all.
