### ISSUE TITLE
Export "Stop Time" in scores/attempts csv

### ISSUE THREAD

**Issue by oscarsiles** [numbas/numbas-lti-provider#62]
It would be useful to be able to extract the date/time a student submits an exam. I can see in the SCORM data that this is already recorded (and is "null" for incomplete attempts), so I assume it shouldn't be too difficult to add? It could also maybe be added as a column on the attempts view on the dashboard?

I haven't had the time to look through the code yet, but might be able to submit a PR soon.

**Comment by christianp** [comment]
Thanks for this suggestion.
