### ISSUE TITLE
Attempts not saving as "completed" correctly

### ISSUE THREAD

**Issue by oscarsiles** [numbas/numbas-lti-provider#86]
Not sure why this is happening, but in testing the latest master branch no attempts seem to be saving as "completed" correctly. When a user submits an exam, it gives a valid verification code and green banner, but shows up as incomplete in all the various user/admin UIs. If the user chooses to "Continue" the attempt, they get sent straight to the post-exam screen.

From what I can tell looking at the attempt JSON, "cmi.completion_status" under "current" is being correctly set to "completed", while the "completion_status" near the top (below "end_time") remains "incomplete".

**Comment by christianp** [comment]
Hi Oscar,
Sorry about this - we made some changes during our exam period, and I think the master branch is in a broken state. The exam period is now over, so I'll have another look. In the mean time, you could revert to commit 541a55473fe3fbd863fae9a97c148ee7c8882e9c.
