### ISSUE TITLE
Uploading an exam fails with an error if multiple LTI items have been launched

### ISSUE THREAD

**Issue by georgestagg** [numbas/numbas-lti-provider#93]
Steps to reproduce:

* Create two numbas LTI items.
* Launch one of the items in a new tab.
* Launch the other one in a new tab.
* Return to the first item's tab and attempt to upload an exam.

The error "Forbidden (403) CSRF verification failed. Request aborted." is shown.

**Comment by christianp** [comment]
This is an instance of #63.
