### ISSUE TITLE
Workers wont keep running, stopping after 1s

### ISSUE THREAD

**Issue by AshCusack** [numbas/numbas-lti-provider#95]
When supervisor is running, the daphne runs find, but the workers are "Starting" and restart after 1s each.  When i check the stdout log i just get the following on every line

> CommandError: You cannot span multiple processes with the in-memory layer. Change your settings to use a cross-process channel layer.

An error log file doesnt seem to have been generated.

**Comment by christianp** [comment]
Did you say 'yes' to the question "Is this installation for development?" while running first_setup.py? That configures the server to use the in-memory channel layer instead of redis.

Replace the `CHANNEL_LAYERS` setting in `numbasltiprovider/settings.py` to the following:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL','redis://localhost:6379')],
            "capacity": 10000,
        },
        "ROUTING": "numbasltiprovider.routing.channel_routing",
    },
}
```

**Comment by AshCusack** [comment]
Thanks Christian.
