### ISSUE TITLE
What is Redis used for?

### ISSUE THREAD

**Issue by lgretton** [numbas/numbas-lti-provider#96]
The installation instructions show that Redis is required, but there is no other mention in the docs about it. I can find nothing useful in the code to indicate what it's used for.

I'm trying to get a rough idea of what size the Redis database is likely to grow to over time so that I can plan an installation.

**Comment by christianp** [comment]
Redis is used by django-channels to pass messages between the different processes. I wouldn't expect the Redis database to grow over time, since the messages are ephemeral - they're discarded once they've been handled.
Does that answer your question?

**Comment by lgretton** [comment]
Thanks for that, I'll close this.
