### ISSUE TITLE
Handle errors with reporting outcomes better

### ISSUE THREAD

**Issue by christianp** [numbas/numbas-lti-provider#97]
@baotn166 reported the request to report outcomes hanging indefinitely because the VLE is not accessible from the LTI server. While this is a misconfiguration, it should be caught and displayed to the user. The POST request in `report_outcome` should at least have a timeout set.

It should also be the case that only one concurrent report process should happen for each resource. They managed to occupy every worker with reporting for the same resource, which made the LTI tool unavailable.

**Comment by christianp** [comment]
@baotn166 let me know if this fixes the problem for you, or at least if it produces an error message that would guide you to a solution.

**Comment by baotn166** [comment]
@christianp thanks, let me check then get back
